# We use the standard Caliper image as a base
FROM hyperledger/caliper:0.5.0

# We manually install the Besu connector so it doesn't have to download at runtime
RUN npm install --save @hyperledger/caliper-besu